/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hzyc_niuben_forslm_opencv_OpenCVHelper */

#ifndef _Included_com_hzyc_niuben_forslm_opencv_OpenCVHelper
#define _Included_com_hzyc_niuben_forslm_opencv_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hzyc_niuben_forslm_opencv_OpenCVHelper
 * Method:    getStringTmp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hzyc_niuben_forslm_1opencv_OpenCVHelper_getStringTmp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
